### ISSUE TITLE
R5 3600X + Intel Xeon CPU E3-1275 v6

### ISSUE THREAD

**Issue by SwenenzY** [ismailkocacan/BenchmarkPointerMath#1]
# R5 3600X (4.4 Ghz)
``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1256 (1909/November2018Update/19H2)
AMD Ryzen 5 3600X, 1 CPU, 12 logical and 6 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT

```
|             Method |     Mean |    Error |   StdDev |
|------------------- |---------:|---------:|---------:|
|     TestClassicFor | 50.40 us | 0.970 us | 0.996 us |
| TestClassicForEach | 50.24 us | 0.997 us | 1.720 us |
|    TestPointerMath | 24.78 us | 0.390 us | 0.325 us |

# Intel Xeon CPU E3-1275 v6 (4.1 Ghz - Not virtual)
``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.17763.1637 (1809/October2018Update/Redstone5)
Intel Xeon CPU E3-1275 v6 3.80GHz, 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.7.2 (4.7.3740.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.7.2 (4.7.3740.0), X64 RyuJIT

```
|             Method |     Mean |    Error |   StdDev |
|------------------- |---------:|---------:|---------:|
|     TestClassicFor | 84.39 us | 1.596 us | 1.838 us |
| TestClassicForEach | 47.50 us | 0.538 us | 0.477 us |
|    TestPointerMath | 25.95 us | 0.064 us | 0.060 us |

**Comment by ismailkocacan** [comment]
@SwenenzY 👍
